export const INCREMENT = "COUNTER_ASYNC_INCREMENT";
export const DECREMENT = "COUNTER_ASYNC_DECREMENT";
export const INCREMENT_ASYNC = "COUNTER_ASYNC_INCREMENT_ASYNC";
export const DECREMENT_ASYNC = "COUNTER_ASYNC_DECREMENT_ASYNC";